name: CI on macos-latest
on:
  push:
    branches: [ main, development, tests_fixes ]
  pull_request:
    branches: [ main ]
jobs:
  test-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Silent install main project
        run: mvn --batch-mode --no-transfer-progress install

      - name: Install xmllint
        run: sudo apt-get install libxml2-utils

      - name: Set current starter version in test-app
        working-directory: ./.github/scripts/
        run: sh set-current-starter-version.sh

      - name: Run automation tests with latest ngrok-spring-boot-starter version on test-app
        working-directory: ./.github/test-app/
        run: mvn --batch-mode --no-transfer-progress test



